#!/bin/bash

export DISPLAY=":0"
xhost +

ITEMS=""

for set in $(ls questions)
do
	ITEMS="$ITEMS $set ."
done

selected=$(dialog --menu "Bitte Antwortenset auswählen" 10 40 10 $ITEMS  3>&1 1>&2 2>&3)
dialog --clear

if [ "$selected" == "" ]; then
	exit 1
fi

players=$(dialog --inputbox "Anzahl der Spieler?" 5 40 "4" 3>&1 1>&2 2>&3)

if [ "$players" == "" ]; then
	exit 1
fi

if [ "$1" == "debug" ]
then
	debug=" debug"
else
	debug=""
fi

echo "Set '$selected' ausgewählt. Starte Jeopardy mit $players Spielern..."
echo

python jeopardy.py "$selected" $players $debug
