#!/bin/bash

export DISPLAY=:0.0
xhost +

SET=($(ls questions))
I=0

for set in "${SET[@]}"
do
	echo "$I: $set"
	I=$(($I + 1))
done
echo
echo "Bitte Fragenset auswählen:"
read choice

if [ "$1" == "debug" ]
then
	debug=" debug"
else
	debug=""
fi

sudo python jeopardy.py  "${SET[$choice]}" $debug
